### ISSUE TITLE
feat: easier permission management for pipelines

### ISSUE THREAD

**Issue by abangser** [syntasso/kratix#192]
By default Kratix creates a service account for use by pipelines. They are deterministically named (using the name of the Promise) and this allows for users to provide permissions to the pipelines using Kubernetes native options such as RBAC. There are two service accounts created per Promise. One for the promise workflows (both configure and delete) and one for the resource workflows (both configure and delete).

While the promise workflows always run in the `kratix-platform-system` namespace, the resource workflows run in the namespace where the request comes into. This is _not_ always deterministic and therefore users right now need to manage copying any data (e.g. secrets or configmaps) and any permissions (e.g. rolebindings) over into each namespace a user might make a request from. This isn't a great experience.

We want permission to be something that is more native to the Promise writing experience and therefore can be created on request rather than separately managed. Some designs are being drawn up, if this is interesting please reach out!

Note: this is different from more control over permissions which will be handed in #193.

**Comment by kirederik** [comment]
We are rethinking the permissions model for the Kratix Pipeline; work will be tracked in these stories:

- [ ] https://github.com/syntasso/kratix/issues/195
- [ ] https://github.com/syntasso/kratix/issues/196
- [ ] https://github.com/syntasso/kratix/issues/197
- [ ] https://github.com/syntasso/kratix/issues/198

**Comment by abangser** [comment]
This issue was covered by the work described above
