### ISSUE TITLE
feat: more control over the permissions model for pipelines

### ISSUE THREAD

**Issue by abangser** [syntasso/kratix#193]
By default Kratix creates a service account for use by pipelines. They are deterministically named (using the name of the Promise) and this allows for users to provide permissions to the pipelines using Kubernetes native options such as RBAC. There are two service accounts created per Promise. One for the promise workflows (both configure and delete) and one for the resource workflows (both configure and delete).

While convenient, this can also be limiting. For example, some users want to provide existing service accounts.

Please feel free to share any other use cases you have for flexibility with pipeline permissions to be included in any implementation designs.

**Comment by kirederik** [comment]
We are rethinking the permissions model for the Kratix Pipeline; work will be tracked in these stories:

- [ ] https://github.com/syntasso/kratix/issues/195
- [ ] https://github.com/syntasso/kratix/issues/196
- [ ] https://github.com/syntasso/kratix/issues/197
- [ ] https://github.com/syntasso/kratix/issues/198

**Comment by abangser** [comment]
This issue was covered by the work above. For more detail check out the docs here: https://docs.kratix.io/main/reference/workflows#rbac
