### ISSUE TITLE
feat: allow promise writers to define permissions across namespaces

### ISSUE THREAD

**Issue by kirederik** [syntasso/kratix#198]
After https://github.com/syntasso/kratix/issues/197, we gave promise writers the ability to define the set of permissions they want associated with the pipeline service account.

In this story, we want to extend that to allow them to also give cross-namespace permissions.

To achieve that, we will introduce a new field in the Pipeline `spec.rbac.permissions`.

It should look something like this:

```yaml
apiVersion: platform.kratix.io/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-name
spec:
  rbac:
    serviceAccount: my-sa # optional
    permissions:
    - apiGroups: [""]
      resources: ["secrets"]
      resourcesNames: ["git-creds"]
      resourcesNamespace: "great-namespace"
      verbs:  ["get"]
  containers:
  - name: hello
    image: myorg/myimage
```

For a pipeline running on the `default` namespace, the above spec should result in the following being created:

* One Kubernetes ClusterRole, containing the rules defined above.
* One Kubernetes RoleBinding on the `resourcesNamespace`, attaching the ClusterRole to the SA on the `default` namespace.

> [!IMPORTANT]
> Updating the `resourcesNamespace` from `A` to `B` should ensure that the RoleBinding created on the namespace `A` is deleted.

We should also allow `resourcesNamespace` to be `*`. In this case, we want to create a ClusterRoleBinding instead of a RoleBinding.

## Tasks
- [x] Introduce the new `rbac.permissions[].resourcesNamespace` field
- [x] Create the ClusterRole and RoleBinding according to the provided values
- [x] When `resourcesNamespaces` is `*`, create a ClusterRoleBinding instead
- [ ] Update docs

**Comment by aclevername** [comment]
explainer: https://stackoverflow.com/questions/71138827/how-to-configure-a-clusterrole-for-namespaced-resources

**Comment by richcooper95** [comment]
Slack thread with some context on progress: https://syntasso.slack.com/archives/C044T9ZFUMN/p1722254781519989
