### ISSUE TITLE
chore: Update docs.kratix.io to use Termly cookie banner

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix#212]
We're now generating our cookie policy via termly, which will automatically update the policy when our cookies change. They provide a consent banner that links to this policy which we should include on our docs site (as well as kratix.io, but I can do that one #Wix4Eva)

You can find the consent banner html snippet in our termly account, login details are in lastpass. Reach out to @catmo-syntasso if you need help finding things

---
### Tasks
- [ ] Remove existing cookie policy codeblock
- [ ] Add termly consent banner html in the <head> section of website [More how to info here](https://support.termly.io/en/articles/7904618-how-to-install-your-consent-banner)
- [ ] Check the new banner appears in the correct format and links to the correct policy

**Comment by kirederik** [comment]
how do i login to the termly account?

**Comment by catmo-syntasso** [comment]
Sent you a share request @kirederik
