### ISSUE TITLE
feat: allow destinations to be configured to write straight to the root of the state store

### ISSUE THREAD

**Issue by kirederik** [syntasso/kratix#234]
We recently introduced `filepath.mode=none` in destinations, which stops kratix from nesting files into directories. However, Kratix will still create at least one directory, named after the destination `metadata.name`. 

There's a good reason why it behaves this way: state stores can be shared across different destinations, and not having a unique top-level directory can lead to file clashes. On the other hand, it's a bit confusing for users to explicitly set it to `none` but still get "one".

A less surprising experience would be if `filepath.mode=none` didn't create any directories at all. Users can still create subdirs for the destination by setting the `spec.path` field. We could also make it configurable via another property.

> [!WARNING]
> Depending on the implementation decision, this may be a breaking change. Consider a migration webhook so it's not

### Scenarios

```gherkin
# Migration for existing Destinatinos
Given a destination set to filepath.mode=none and path=subdir
When I upgrade Kratix to the latest version
Then the migration webhook updates my Destination
And the `spec.path` migrates from `subdir` to `<destination name>/subdir`

# Brand new destination
Given a destination set to filepath.mode=none and path=nil
When a workplacement is created for that destination
Then it's written to the root directory
```

**Comment by aclevername** [comment]
+1 to this. When leveraging an existing TFE workspace, its often pointed at the root of a git repo. This means that if I want to use an existing TFE workspace with Kratix, I have to change it to use the sub dir, which is frustrating.

**Comment by kirederik** [comment]
The destination object looks like this:

```yaml
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: destination-name
  labels:
    environment: dev
spec:
  path: path/in/statestore
  strictMatchLabels: false
  filepath:
    mode: nestedByMetadata | none
  cleanup: none
  stateStoreRef:
    name: default
    kind: BucketStateStore
```

The ideal scenario in my mind would be one where Kratix would just stop writing the destination name as a main path altogether. Users could use `path` if they wanted a directory at the root of the repository.

That would be a breaking change. Not sure we can write a migration without bumping the apiVersion though.

Another alternative is to maybe introduce another spec field? Something like what's down below:

```yaml
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: destination-name
  labels:
    environment: dev
spec:
  # defaults to destinationName
  root: destinationName | none 
  prefix: destinationName | none
  
  # defaults to false
  skipDestinationNameDir: true | false
```

or something like that. Would that be more confusing?

A third alternative is to make add another `filepath.mode`. Maybe `root`?


 wdyt @aclevername @catmo-syntasso (@abangser usually have opinions on names :p)

**Comment by abangser** [comment]
IIRC, we use the `path` field in the statestore with a default in order to reduce the footprint of our API.

I think we spoke about that for here too. As in, instead of prefix and root, we just put `path` and enable people to put anything they want, possibly providing ease of use envvars. 

Could we do a migration from the current `filepath` + `path` to `path` only and then let people just null out path?

If that isn't sensible, then I would prefer to see us put this into filepath mode rather than an additional spot. Possibly breaking change to `none` as this would be true none, or introducing `root`.

**Comment by kirederik** [comment]
https://github.com/syntasso/kratix/pull/352

attempted to implement a webhook to change the behaviour of `path` entirely 👀

**Comment by kirederik** [comment]
OK, here's my Formal Proposal, following the guidelines from [WikiHow](https://www.wikihow.com/Write-a-Proposal).


## The issue 

![Image](https://github.com/user-attachments/assets/f197ebac-4d2e-4a23-a0cc-8a53ff84394b)

Today, whenever the user create a Destination, Kratix will create a directory with the destination name in the State Store and will push a couple of test documents.

Users have the following levers to configure the path that Kratix uses on the State Store:

* In the State Store itself, there's an optional `spec.path` field
* In the Destination:
  * there's an optional `spec.path` field
  * there's a `filepath.mode` field

For `filepath.mode=nestedByMetadata` (the default), Kratix will write following a pattern like this:

```
<StateStore.path> / <Destination.path> / <Promise.name> / <Resource.namespace> /  <Resource.name> / <workflow files>
```

For `filepath.mode=none`:

```
<StateStore.path> / <Destination.name> / <Destination.path> / <workflow files>
```

However, for some use cases like integrating with existing systems or terraform, users want to define the _full path_ themselves, sometimes even writing to the root of the state store altogether.

That means we need to provide a way for them to _not_ end up with the `destination name` on the path.

## The Solution

![Image](https://github.com/user-attachments/assets/005df3bf-4667-4cae-aeb0-7a23b331a440)

Currently, the Destination object looks like this:

```yaml
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: destination-name
  labels:
    environment: dev
spec:
  path: path/in/statestore # optional
  strictMatchLabels: false
  filepath:
    mode: nestedByMetadata | none
  cleanup: none
  stateStoreRef:
    name: default
    kind: BucketStateStore
```

The first thing that comes to mind as a solution is to just get rid of the destination name from the path entirely.

The danger of this solution is that it may lead users to errors, since if you register two destinations on the same state store, but forget to define different `spec.path` on the destinations, the documents will all be written to the root directory.

> [!NOTE]
> We could create a Validation webhook that checks all the destinations writing to the same state store, and fail (or warn) if we detect possible conflicts.

This is a breaking change that's quite difficult to circumvent. We would need to patch destinations existing prior to the upgrade, but somehow know that, for newer destinations, that could be empty.

An alternative solution is to make `spec.path` mandatory. Making it mandatory would force the user to think about it, and consciously choose a path. We define `/` or `.` as "the root path".

If we do make it mandatory, we can introduce some logic in Kratix that would automatically patch any pre-existing Destination with `spec.path = destination name` if the path is not set; this would make this change a non-breaking change.

> [!NOTE]
> Although we can make this a not-breaking-change for existing, live Kratix, all scripts generating Destinations on a brand-new Kratix may need to be updated so Destinations include a path.

I believe that making it mandatory makes the most sense. It's easy to migrate, it does not represent _extra_ cognitive load (users already have to reason about the path, even if they leave it as empty).

## Summary

![Image](https://github.com/user-attachments/assets/1d934cc3-f70a-4ef8-a8b1-504a2f12c462)

* Make `spec.path` mandatory
* Write migration logic into the kratix controller that patch any existing destination with a path
* Update scripts and examples everywhere

**Comment by kirederik** [comment]
## TODO

- [ ] Write the code with test
- [ ] Update destination helm-charts with some default in the path
- [ ] Update examples
- [ ] Update docs
- [ ] Update demos
- [ ] Add validation webhook to ensure there are no conflicting paths

**Comment by abangser** [comment]
Only a couple of small questions

1. Does this makes the file path field redundant and if so will we be removing it? 
2. A nice to have enhancement is to be able to construct the full file path from variables we can interpolate. So being and to nest by things that include the destination name but do so via variables. 

Thanks for the clear write-up and party forward @kirederik !

**Comment by kirederik** [comment]
> Does this makes the file path field redundant and if so will we be removing it?

No, it's still needed to determine if kratix will be writing in subfolders within the path or not. We could look into simplifying it though, maybe merging... but will leave it as a subsequent improvement

> A nice to have enhancement is to be able to construct the full file path from variables we can interpolate. So being and to nest by things that include the destination name but do so via variables.

That's for what is currently being controlled by the `filepath.mode` right? If so, agree!
